# Generated by Django 4.2.3 on 2023-10-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='Year',
            new_name='year',
        ),
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='daedssff', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
